// GENERATED by scripts/gen_browser_rules.py from devhound/secrets.py. Do not edit by hand.
var DH_RULES = {
  "patterns": [
    {
      "id": "DH-SEC-002",
      "name": "AWS access key ID",
      "source": "\\b(?:AKIA|ASIA)[0-9A-Z]{16}\\b",
      "flags": ""
    },
    {
      "id": "DH-SEC-003",
      "name": "GitHub token",
      "source": "\\b(?:gh[pousr]_[A-Za-z0-9]{36,}|github_pat_[A-Za-z0-9_]{50,})\\b",
      "flags": ""
    },
    {
      "id": "DH-SEC-004",
      "name": "Slack token",
      "source": "\\bxox[abprs]-[A-Za-z0-9-]{10,}\\b",
      "flags": ""
    },
    {
      "id": "DH-SEC-005",
      "name": "Private key block",
      "source": "-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY(?: BLOCK)?-----",
      "flags": ""
    },
    {
      "id": "DH-SEC-006",
      "name": "Google API key",
      "source": "\\bAIza[0-9A-Za-z_\\-]{35}\\b",
      "flags": ""
    },
    {
      "id": "DH-SEC-007",
      "name": "Stripe live key",
      "source": "\\b(?:sk|rk)_live_[0-9A-Za-z]{20,}\\b",
      "flags": ""
    },
    {
      "id": "DH-SEC-008",
      "name": "DevHound personal access token",
      "source": "\\bdh_pat_[A-Za-z0-9]{24,}\\b",
      "flags": ""
    }
  ],
  "generic": {
    "id": "DH-SEC-001",
    "name": "Hardcoded secret-like value",
    "source": "\\b(?:api[_-]?key|secret|token|passw(?:or)?d|auth)\\w*\\s*[:=]\\s*[\"']([^\"'\\s]{16,})[\"']",
    "flags": "i",
    "minEntropy": 3.5
  },
  "ignoreMarker": "devhound:ignore"
};
if (typeof module !== "undefined") { module.exports = DH_RULES; }
