# devhound shell integration for bash and zsh. GENERATED by scripts/gen_completions.py; do not edit by hand.
# Add to ~/.bashrc or ~/.zshrc:   source /path/to/Lil_B/addons/shell/devhound.sh
# Gives you: tab-completion for devhound, and `dh` (scan + funding check + brand check in one word).

if [ -n "${ZSH_VERSION:-}" ]; then
  autoload -U +X bashcompinit 2>/dev/null && bashcompinit 2>/dev/null
fi

_devhound() {
  local cur prev sub opts choices
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  COMPREPLY=()
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "check scan brand hooks init doctor mascot --help --version" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --format) COMPREPLY=( $(compgen -W "text json sarif" -- "$cur") ); return 0;;
    --output|-o) COMPREPLY=( $(compgen -f -- "$cur") ); return 0;;
  esac
  sub="${COMP_WORDS[1]}"
  opts=""; choices=""
  case "$sub" in
    check) opts="--format --help --if-present --output --strict"; choices="";;
    scan) opts="--format --help --output --staged"; choices="";;
    brand) opts="--format --help --output --update-checksums"; choices="";;
    hooks) opts="--force --help --shared"; choices="install uninstall status";;
    init) opts="--help"; choices="";;
    doctor) opts="--help"; choices="";;
    mascot) opts="--help"; choices="";;
  esac
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$opts --help" -- "$cur") )
  elif [ -n "$choices" ]; then
    COMPREPLY=( $(compgen -W "$choices" -- "$cur") )
  else
    COMPREPLY=( $(compgen -f -- "$cur") )
  fi
  return 0
}
complete -o default -F _devhound devhound

# Run devhound whether or not it is installed on PATH (falls back to python3 -m devhound).
_dh_run() {
  if command -v devhound >/dev/null 2>&1; then devhound "$@"; else python3 -m devhound "$@"; fi
}

# dh: run every applicable check and print one line each. Exit code is non-zero if any failed.
dh() {
  local rc=0 tmp line
  tmp="$(mktemp)" || return 2
  _dh_step() {
    local name="$1"; shift
    _dh_run "$@" 2>"$tmp"
    local code=$?
    line="$(tail -n 1 "$tmp")"
    if [ "$code" -eq 0 ]; then printf '\033[32m✓\033[0m %-7s %s\n' "$name" "${line#* }"; else printf '\033[31m✗\033[0m %-7s %s\n' "$name" "${line#* }"; rc=1; fi
  }
  _dh_step scan scan .
  _dh_step funding check --if-present
  [ -f assets/logo/CHECKSUMS.sha256 ] && _dh_step brand brand
  rm -f "$tmp"
  unset -f _dh_step
  return $rc
}
