#!/usr/bin/env python3
"""Generate addons/browser/rules.js from devhound/secrets.py so the extension can't drift from the CLI.

Run:  python3 scripts/gen_browser_rules.py          (rewrite the file)
      python3 scripts/gen_browser_rules.py --check  (exit 1 if out of date)
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from devhound import secrets  # noqa: E402
from devhound.sarif import _RULES  # noqa: E402

OUT = os.path.join(ROOT, "addons", "browser", "rules.js")


def _flags(rx):
    return "i" if rx.flags & re.I else ""


def render():
    patterns = [{"id": rid, "name": name, "source": rx.pattern, "flags": _flags(rx)} for rid, name, rx in secrets.PATTERNS]
    g = secrets.GENERIC
    src = g.pattern
    flags = "i" if g.flags & re.I else ""
    if src.startswith("(?ix)"):  # inline flags are not valid in JS
        src, flags = src[5:], "i"
    rules = {
        "patterns": patterns,
        "generic": {"id": "DH-SEC-001", "name": _RULES["DH-SEC-001"], "source": src, "flags": flags, "minEntropy": 3.5},
        "ignoreMarker": secrets.INLINE_IGNORE,
    }
    return ("// GENERATED by scripts/gen_browser_rules.py from devhound/secrets.py. Do not edit by hand.\n"
            "var DH_RULES = " + json.dumps(rules, indent=2) + ";\n"
            'if (typeof module !== "undefined") { module.exports = DH_RULES; }\n')


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        current = open(OUT).read() if os.path.exists(OUT) else ""
        sys.exit(0 if current == text else 1)
    open(OUT, "w").write(text)
    print("wrote", OUT)
