#!/usr/bin/env python3
"""Generate addons/shell/devhound.sh (tab-completion + `dh`) from the real argparse definition.

Run:  python3 scripts/gen_completions.py          (rewrite)
      python3 scripts/gen_completions.py --check  (exit 1 if out of date)
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from devhound.cli import build_parser  # noqa: E402

OUT = os.path.join(ROOT, "addons", "shell", "devhound.sh")


def introspect():
    parser = build_parser()
    sub = next(a for a in parser._actions if a.dest == "cmd")
    info = {}
    for name, sp in sub.choices.items():
        opts, choices = [], []
        for act in sp._actions:
            opts += [o for o in act.option_strings if o.startswith("--")]
            if not act.option_strings and act.choices:
                choices += list(act.choices)
        info[name] = (sorted(set(opts)), choices)
    return info


def render():
    info = introspect()
    cases = []
    for name, (opts, choices) in info.items():
        cases.append(f'    {name}) opts="{" ".join(opts)}"; choices="{" ".join(choices)}";;')
    body = "\n".join(cases)
    cmds = " ".join(info)
    return f'''# devhound shell integration for bash and zsh. GENERATED by scripts/gen_completions.py; do not edit by hand.
# Add to ~/.bashrc or ~/.zshrc:   source /path/to/Lil_B/addons/shell/devhound.sh
# Gives you: tab-completion for devhound, and `dh` (scan + funding check + brand check in one word).

if [ -n "${{ZSH_VERSION:-}}" ]; then
  autoload -U +X bashcompinit 2>/dev/null && bashcompinit 2>/dev/null
fi

_devhound() {{
  local cur prev sub opts choices
  cur="${{COMP_WORDS[COMP_CWORD]}}"
  prev="${{COMP_WORDS[COMP_CWORD-1]}}"
  COMPREPLY=()
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "{cmds} --help --version" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --format) COMPREPLY=( $(compgen -W "text json sarif" -- "$cur") ); return 0;;
    --output|-o) COMPREPLY=( $(compgen -f -- "$cur") ); return 0;;
  esac
  sub="${{COMP_WORDS[1]}}"
  opts=""; choices=""
  case "$sub" in
{body}
  esac
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$opts --help" -- "$cur") )
  elif [ -n "$choices" ]; then
    COMPREPLY=( $(compgen -W "$choices" -- "$cur") )
  else
    COMPREPLY=( $(compgen -f -- "$cur") )
  fi
  return 0
}}
complete -o default -F _devhound devhound

# Run devhound whether or not it is installed on PATH (falls back to python3 -m devhound).
_dh_run() {{
  if command -v devhound >/dev/null 2>&1; then devhound "$@"; else python3 -m devhound "$@"; fi
}}

# dh: run every applicable check and print one line each. Exit code is non-zero if any failed.
dh() {{
  local rc=0 tmp line
  tmp="$(mktemp)" || return 2
  _dh_step() {{
    local name="$1"; shift
    _dh_run "$@" 2>"$tmp"
    local code=$?
    line="$(tail -n 1 "$tmp")"
    if [ "$code" -eq 0 ]; then printf '\\033[32m✓\\033[0m %-7s %s\\n' "$name" "${{line#* }}"; else printf '\\033[31m✗\\033[0m %-7s %s\\n' "$name" "${{line#* }}"; rc=1; fi
  }}
  _dh_step scan scan .
  _dh_step funding check --if-present
  [ -f assets/logo/CHECKSUMS.sha256 ] && _dh_step brand brand
  rm -f "$tmp"
  unset -f _dh_step
  return $rc
}}
'''


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if os.path.exists(OUT) and open(OUT).read() == text else 1)
    open(OUT, "w").write(text)
    print("wrote", OUT)
